package v4l2

const (
	VIDIOC_QUERYCAP  = 0
	VIDIOC_ENUM_FMT  = 2
	VIDIOC_G_FMT     = 4
	VIDIOC_S_FMT     = 5
	VIDIOC_REQBUFS   = 8
	VIDIOC_QUERYBUF  = 9
	VIDIOC_QBUF      = 15
	VIDIOC_DQBUF     = 17
	VIDIOC_STREAMON  = 18
	VIDIOC_STREAMOFF = 19
)
